---
- name: 'Baixa o arquivo de instalacao do Wordpress'
  get_url:
    url: https://wordpress.org/latest.tar.gz'
    dest: '/tmp/wordpress.tar.gz'
- name: 'Descompacta o wordpress'
  unarchive:
    src: '/tmp/wordpress.tar.gz'
    dest: /var/www/
    remote_src: yes
  become: yes
- name: "Mudando nome do arquivo no wordpress"
  copy:
    src: "{{ wp_installation_dir }}/wp-config-sample.php"
    dest: "{{ wp_installation_dir }}/wp-config.php"
    remote_src: yes
  become: yes
- name: 'Configura o wp-config com as entradas do banco de dados'
  replace:
    path: "{{ wp_installation_dir }}/wp-config.php"
    regexp: "{{ item.antigo }}"
    replace: "{{ item.novo }}"
    backup: yes
  loop:
    - { antigo: 'database_name_here', novo: "{{ wp_db_name }}" }
    - { antigo: 'username_here', novo: "{{ wp_user_name }}" }
    - { antigo: 'password_here', novo: "{{ wp_user_password }}" }
    - { antigo: 'localhost', novo: '172.17.177.42'}
  become: yes
- name: 'Configura Apache para servir o Wordpress usando template'
  template:
    src: 'templates/000-default.conf'
    dest: '/etc/apache2/sites-available/000-default.conf'
  become: yes
  notify:
   - reinicia apache
